gText_Birch_Welcome:: @ 82C897B
	.string "Greetings and welcome to Elara\p" 
    .string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This region is inhabited by:\n"
    .string "Creatures known as Pokémon.\p"
    .string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
    .string "Some people keep Pokémon as pets.\p"
    .string "Others called trainers battle with\n"
    .string "them.\p"
    .string "Me personally?\p"
    .string "I'm a Pokémon professor, that\n"
    .string "studies the bond between trainer\p"
    .string "and their Pokémon\p"
    .string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "But tell me about yourself\p"
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "And what's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Nice to meet you {PLAYER}{KUN}.\p"
	.string "You must be one of the students \n"
	.string "from Deneb Academy…\p"
	.string " OH!!\p"
    .string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "I have to get back to my studies,\n"
	.string "perhaps I will meet you soon?\p"
    .string "$"
